### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by chayleaf** [leminhyen2/Visual-Novel-OCR#16]
Without a license, it's actually illegal to do *anything* with the code. I recommend adding an open-source license such as MIT/Apache (attribution required, distributing proprietary forks allowed) or GPL (attribution required, distributing derivatives requires source code disclosure). You may also opt for 0BSD to allow anyone to do absolutely anything with the code without attribution. I personally use all of the mentioned licenses depending on the use case.

**Comment by leminhyen2** [comment]
Ok, I just added GNU license. You can check it out. I am more active on Discord not on Github so sometimes I missed posts here
