### ISSUE TITLE
Doesn't play nice with some programs

### ISSUE THREAD

**Issue by rampaa** [leminhyen2/Visual-Novel-OCR#17]
Visual Novel OCR becomes extremely laggy if [Discord Sandboxed ](https://github.com/khlam/discord-sandboxed#discord-sandbox-) is open. It's so bad that my mouse barely moves when I try to run it without shutting Discord Sandboxed down first.

**Comment by leminhyen2** [comment]
Since my program is an Electron app, which is the same as Discord. Maybe Discord Sandboxed is flagging VN OCR as Discord

**Comment by rampaa** [comment]
"Discord Sandboxed" doesn't flag the Discord app though, it's a standalone Discord app replacement for better privacy. So I don't think it can flag VN OCR as Discord, or anything of the sort.

And I believe Discord Sandboxed is not the only app VN OCR is not playing nice with. I searched in your Discord server to see if anyone else had this lagging problem and found someone who had it. In their case though it was an app called "Gilded" (apparently a "Discord ripoff") that needed to be closed in order to prevent VN OCR from making their whole PC lag like crazy.

**Comment by leminhyen2** [comment]
Ok, thanks for letting me know. That could help some users if they can't get VN OCR to work
