### ISSUE TITLE
Làm bản 32bit cho máy yếu Win7

### ISSUE THREAD

**Issue by tbhoang12** [leminhyen2/Visual-Novel-OCR#5]
chào bác chủ thớt , bác có thể làm phiên bản 32bit dành cho máy yếu dc ko ạ ?
Em có dùng vài phần mêm như Capture2Text với Easy Screen OCR nhưng mà hiệu quả bắt từ Nhât rất kém (có chữ bắt sai rất nhiều) .Chủ yếu em chỉ cần hiểu mấy cái hình giao diện UI với nút bấm thôi còn văn bản trong game đã có Textractor rồi 

Mong bác phát triển thêm phiên bản 32bit gọn nhẹ cho máy yếu như em (e dùng Win7 Ultimate 32bit ).Cám ơn bác o/

**Comment by leminhyen2** [comment]
Căn bản là máy dùng để dev là Win 10 64 bit nên ko thử đc Win 7 32 bit, bác thông cảm.
